const lib = require("../solutions/lib/day11");

test("SolveFirstStar", () => {
	let lines = [];
	lines.push("Monkey 0:");
	lines.push("  Starting items: 79, 98");
	lines.push("  Operation: new = old * 19");
	lines.push("  Test: divisible by 23");
	lines.push("    If true: throw to monkey 2");
	lines.push("    If false: throw to monkey 3");
	lines.push("");
	lines.push("Monkey 1:");
	lines.push("  Starting items: 54, 65, 75, 74");
	lines.push("  Operation: new = old + 6");
	lines.push("  Test: divisible by 19");
	lines.push("    If true: throw to monkey 2");
	lines.push("    If false: throw to monkey 0");
	lines.push("");
	lines.push("Monkey 2:");
	lines.push("  Starting items: 79, 60, 97");
	lines.push("  Operation: new = old * old");
	lines.push("  Test: divisible by 13");
	lines.push("    If true: throw to monkey 1");
	lines.push("    If false: throw to monkey 3");
	lines.push("");
	lines.push("Monkey 3:");
	lines.push("  Starting items: 74");
	lines.push("  Operation: new = old + 3");
	lines.push("  Test: divisible by 17");
	lines.push("    If true: throw to monkey 0");
	lines.push("    If false: throw to monkey 1");
	expect(lib.solveForFirstStar(lines)).toBe(10_605);
});

test("SolveSecondStar", () => {
	let lines = [];
	lines.push("Monkey 0:");
	lines.push("  Starting items: 79, 98");
	lines.push("  Operation: new = old * 19");
	lines.push("  Test: divisible by 23");
	lines.push("    If true: throw to monkey 2");
	lines.push("    If false: throw to monkey 3");
	lines.push("");
	lines.push("Monkey 1:");
	lines.push("  Starting items: 54, 65, 75, 74");
	lines.push("  Operation: new = old + 6");
	lines.push("  Test: divisible by 19");
	lines.push("    If true: throw to monkey 2");
	lines.push("    If false: throw to monkey 0");
	lines.push("");
	lines.push("Monkey 2:");
	lines.push("  Starting items: 79, 60, 97");
	lines.push("  Operation: new = old * old");
	lines.push("  Test: divisible by 13");
	lines.push("    If true: throw to monkey 1");
	lines.push("    If false: throw to monkey 3");
	lines.push("");
	lines.push("Monkey 3:");
	lines.push("  Starting items: 74");
	lines.push("  Operation: new = old + 3");
	lines.push("  Test: divisible by 17");
	lines.push("    If true: throw to monkey 0");
	lines.push("    If false: throw to monkey 1");
	expect(lib.solveForSecondStar(lines)).toBe(2713310158);
});
